## Tensors

+ Tensors are a specialized data structure that are very similar to arrays an matrices. 
In PyTorch, tensors are used to encode the inputs and output of a model, as well as the paramters of the model
+ Tensors are similat to NumPy's `ndarrays`, except that tensors can run on GPUs or other hardware accelerators
+ Tensors are also optimized for automatic differentiation

In [23]:
import torch
import numpy as np

### Initializing a Tensor

#### Directly from data

In [24]:
data = [[[1,2],[3,4],[5,6]]]
x_data = torch.tensor(data)
x_data

tensor([[[1, 2],
         [3, 4],
         [5, 6]]])

#### From a NumPy array

In [25]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[[1, 2],
         [3, 4],
         [5, 6]]])

#### From another tensor
+ The new tensor retais the properties (shape, datatype) or the argument tensor

In [26]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[[1, 1],
         [1, 1],
         [1, 1]]]) 



In [27]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[[0.1092, 0.5966],
         [0.7199, 0.8766],
         [0.3046, 0.2092]]]) 



#### With random or constant values

+ `shape` is a tuple of tensor dimensions

shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeroes Tensor: \n {zeros_tensor} \n")

---

### Attributes of a Tensor

In [28]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


---

### Operations on Tensors

+ Over 100 tensor operations, including arithmetic, linear algebra, matrix manipulation, sampling, etc...
+ Each can be run on a GPU; by default tensors are created on the CPU

In [29]:
## move the tensor to the GPU is available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

#### Standard numpy-like indexing and slicing:

In [30]:
tensor = torch.ones(4,4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:,0]}")
print(f"Last column: {tensor[...,-1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


#### Joining tensors
+ Can use `torch.cat` to concatenate a sequence of tensors along a given dimension
+ Can also use `torch.stack`, another joining operation

In [31]:
t1 = torch.cat([tensor, tensor, tensor],dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


#### Arithmetic operations

In [34]:
## This computes the matrix multiplication between 2 tensors
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

## This computes the element-wise product
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

#### Single-element tensors
+ can convert a one-element tensor to a Python numerical value using `item()`

In [35]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


#### In-place operations
+ operations that store the result into the operand are -inplace; denoted by a `_ suffix`

In [36]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


---

## Bridge with NumPy
+ Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other

In [38]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [40]:
# a change in the tensor reflects in the array
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


#### NumPy Array to Tensor

In [41]:
n = np.ones(5)
t = torch.from_numpy(n)

In [43]:
# changes in the NumPy array reflects in the tensor
np.add(n,1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
