In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.2


## Introduction to tensors

### Creating tensors
PyTorch tensors are ceating usng `torch.Tensor()`

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [6]:
# get tensor back as Python int
scalar.item()

7

In [7]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [12]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
MATRIX[0], MATRIX[1]

(tensor([7, 8]), tensor([ 9, 10]))

In [17]:
## TENSOR
TENSOR = torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [18]:
TENSOR.ndim

3

In [19]:
TENSOR.shape

torch.Size([1, 3, 3])

In [20]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [22]:
TENSOR[0][0]

tensor([3, 6, 9])

In [26]:
## NEW TENSOR
TENSOR_NEW = torch.tensor([[[34,5,20],[9,0,7],[33,34,6]]])
TENSOR_NEW.ndim

3

In [27]:
TENSOR_NEW.shape

torch.Size([1, 3, 3])

In [28]:
TENSOR_NEW[0][0]

tensor([34,  5, 20])

### Random Tensors

Why random tensors?
Random tensors are imporant because the way many neural networks learn is they start with tensors full of rnadom #s and then ajudst to better represent the data.

`Start with random numbers -> look at data -> update random #s -> look at data -> update`

In [40]:
## create a random tensor of size/shahpe (3,4)
random_tensor = torch.rand(5,4)
random_tensor

tensor([[0.5055, 0.1656, 0.0925, 0.0538],
        [0.8701, 0.3482, 0.6660, 0.9894],
        [0.7582, 0.2347, 0.2319, 0.6715],
        [0.4206, 0.0397, 0.3502, 0.4917],
        [0.2794, 0.8835, 0.3043, 0.5632]])

In [41]:
random_tensor

tensor([[0.5055, 0.1656, 0.0925, 0.0538],
        [0.8701, 0.3482, 0.6660, 0.9894],
        [0.7582, 0.2347, 0.2319, 0.6715],
        [0.4206, 0.0397, 0.3502, 0.4917],
        [0.2794, 0.8835, 0.3043, 0.5632]])

In [34]:
random_tensor = torch.rand(5,4)
random_tensor.ndim

2

In [35]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels (RBG)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [39]:
random_tensor = torch.rand(5,10,10)
random_tensor.ndim, random_tensor.shape

(3, torch.Size([5, 10, 10]))

### Zeroes and ones

In [42]:
# create a tensor of all zeoros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [45]:
# create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [46]:
ones.dtype

torch.float32

In [47]:
random_tensor.dtype

torch.float32

### Create a range of tensors and tensors-like

In [55]:
# use torch.arange()
# torch.range deprecated
one_to_ten=torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
## Creating tensors like
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
ten_zeros = torch.zeros_like(input=one_to_ten)

In [58]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note** Tensor datatypes is one of the 3 big building blocks/potential sources of errors with PyTorch and deep learning;
1. Need the right datatype to perform certain operations
2. Need the right shape of the data
3. Tensor needs to be on the appropriate/right device

In [59]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [60]:
# default data type to come out as float 32
float_32_tensor.dtype

torch.float32

In [62]:
# Float 32 tensor
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [67]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what type of unit the data is - 16 bit, 32 bit vs 64 bit
                               device=None, # what device the tensor is on; ex: 'cuda', etc
                               requires_grad=False) # if want PyTorch to track the gradients of a tensor

In [68]:
float_32_tensor.dtype

torch.float32

In [70]:
# converting from float32 to float16
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [71]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [72]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [73]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting Information from Tensors - tensor Attributes
1. Tensor datatype - can use `tensor.dtype`
2. Tensor shape - can use `tensor.shape`
3. Tensor device - can use `tensor.device`

In [74]:
# create a tesnor
some_tensor = torch.rand(10,7)
some_tensor

tensor([[0.9790, 0.0458, 0.3106, 0.7965, 0.6215, 0.8551, 0.2990],
        [0.3251, 0.4151, 0.0164, 0.5517, 0.3654, 0.7158, 0.0907],
        [0.0379, 0.3858, 0.1312, 0.6793, 0.4716, 0.2112, 0.3022],
        [0.0138, 0.6929, 0.3943, 0.5343, 0.7413, 0.1514, 0.0130],
        [0.9926, 0.9625, 0.5674, 0.9766, 0.9008, 0.1216, 0.9009],
        [0.3191, 0.8245, 0.7830, 0.1163, 0.7014, 0.0138, 0.8514],
        [0.6100, 0.5052, 0.7938, 0.4392, 0.9769, 0.8048, 0.4048],
        [0.2374, 0.4357, 0.6805, 0.2195, 0.1414, 0.1892, 0.5889],
        [0.7232, 0.6959, 0.5188, 0.2207, 0.3773, 0.0745, 0.8779],
        [0.0570, 0.8915, 0.7974, 0.6948, 0.2931, 0.4159, 0.4336]])

In [76]:
# find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Tensor is on device: {some_tensor.device}")

tensor([[0.9790, 0.0458, 0.3106, 0.7965, 0.6215, 0.8551, 0.2990],
        [0.3251, 0.4151, 0.0164, 0.5517, 0.3654, 0.7158, 0.0907],
        [0.0379, 0.3858, 0.1312, 0.6793, 0.4716, 0.2112, 0.3022],
        [0.0138, 0.6929, 0.3943, 0.5343, 0.7413, 0.1514, 0.0130],
        [0.9926, 0.9625, 0.5674, 0.9766, 0.9008, 0.1216, 0.9009],
        [0.3191, 0.8245, 0.7830, 0.1163, 0.7014, 0.0138, 0.8514],
        [0.6100, 0.5052, 0.7938, 0.4392, 0.9769, 0.8048, 0.4048],
        [0.2374, 0.4357, 0.6805, 0.2195, 0.1414, 0.1892, 0.5889],
        [0.7232, 0.6959, 0.5188, 0.2207, 0.3773, 0.0745, 0.8779],
        [0.0570, 0.8915, 0.7974, 0.6948, 0.2931, 0.4159, 0.4336]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([10, 7])
Tensor is on device: cpu


### Manipulating tensors (Tensor Operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [77]:
# create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor +10

tensor([11, 12, 13])

In [78]:
## multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [79]:
# subtract 10
tensor - 10

tensor([-9, -8, -7])

In [80]:
# try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Multiplication

Two main ways of performing multiplication in neural nets and deep learning

1. Element-wise multiplication
2.  Matrix multiplication (aka dot product)

In [83]:
## Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [90]:
## Matrix multiplication

torch.matmul(tensor, tensor)

tensor(14)

In [86]:
# Matrix multiplication by hand
(1*1) + (2*2) + (3*3)

14

In [91]:
%%time 
value=0
for i in range(len(tensor)):
    value += tensor[i]*tensor[i]
value ## 1.77 milliseconds

CPU times: user 1.66 ms, sys: 976 µs, total: 2.64 ms
Wall time: 1.77 ms


tensor(14)

In [94]:
%%time
torch.matmul(tensor, tensor) ## 589 micro-seconds
# also can use `@` for matrix multiplication

CPU times: user 508 µs, sys: 124 µs, total: 632 µs
Wall time: 596 µs


tensor(14)

### Matrix Multiplication - Two Main Rules

One of the most common errors in deep learning is shape error

**`Rule 1`**: The **inner dimensions** must match
* `(3,2) @ (3,2)` - won't work
* `(2,3) @ (3,2)` - will work
* `(3, 2) @ (2,3)` - will work
  
**`Rule 2`**: The resulting matrix has a shape of the **outer dimensions**
* `(2,3) @ (3,2)` -> `(2,2)`
*  `3,2 @ (2,3)` -> `(3,3)`

In [95]:
torch.rand(3,2).shape

torch.Size([3, 2])

In [97]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.2353, 0.1603, 0.2170],
        [0.3643, 0.2307, 0.3567],
        [0.3467, 0.2316, 0.3251]])

In [100]:
torch.matmul(torch.rand(10,10), torch.rand(10,10)).shape

torch.Size([10, 10])